### PR TITLE
Html type added in message transaction

### PR DESCRIPTION
**Pull request by serhankilicarslan**
Added html content for advanced messages.

### CODE REVIEW

**Comment by akshay2000** [comment]
Is there a reason this hasn't been merged yet? I'd really like this functionality.

**Comment by moinism** [comment]
@akshay2000 Can you please resolve the file conflicts? I'll merge it then.

**Comment by akshay2000** [comment]
@moinism Thanks! Let's wait for @serhankilicarslan for a bit since he did all the work.

**Comment by serhankilicarslan** [comment]
@moinism I resolved the conflicts.

**Comment by akshay2000** [comment]
@moinism Can you review and merge this now, please?

**Pull request merged**
