### PR TITLE
fixed markdown processing bug, fixes #66 fixes #78 fixes #34

### LINKED ISSUE #34: Markup rendering fails with delay option and Vue >2.0.7
E.g.: Links are not rendered when the message is delayed and the Vue version is greater than 2.0.7.

You can play with [this Codepen](https://codepen.io/esaborit4code/pen/baowjw) to check the behaviour when changing Vue's version or setting the `delay` option.

I currently have no idea about Vue, but I hope this helps.

Thank you.

### LINKED ISSUE #66: markdown images are not appearing
Hi, I can not get the markdown images working.

Here is my code:
```
(...)

this.bot = new BotUI('my-botui-app');
this.bot.message.add({
      content: 'Hey! 👋',
      cssClass: 'botui-no-icon',
      delay: 1000
})
.then(() => this.bot.message.add({
      cssClass: 'botui-no-icon',
      content: 'Here is an image ![product image](https://cdn.pixabay.com/photo/2016/06/18/17/42/image-1465348_960_720.jpg)',
      delay: 500
}));

(...)
```

The visual output is:
`Here is an image `

also, inspecting the HTML:
```
<div class="botui-message-content text"><span>Here is an image </span> <!----></div>
```
you can see, that it is just empty…

There are no JS errors in console…

- I used version `0.3.4` of your bot.
- I am on `Version 66.0.3359.181 (Official Build) (64-bit)`

### LINKED ISSUE #78: Markdown image is deleted by the next message
I cannot reproduce this with the default usage of botui : the issue appears only when botui is part of a larger VueJS app.

When a markdown image is inserted in a message, it is immediately hidden if another message is displayed after.
```javascript
botui.message.add({
	content: 'Hello World'
});
botui.message.add({
	content: 'Here is a picture : ![](https://www.google.fr/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png)'
});
botui.message.add({
	content: '.. that disappears if it is followed by another message'
});
```

The issue is that the `botui-markdown` directive is executed for each message each time a new message is posted. 
```javascript
root.Vue.directive('botui-markdown', function (el, binding) {
      if(binding.value == 'false') return; // v-botui-markdown="false"
      el.innerHTML = _parseMarkDown(el.textContent);
});
```
I was able to fix this by marking the node as already parsed
```javascript
root.Vue.directive('botui-markdown', function (el, binding) {
    if(binding.value == false || el.getAttribute('botui-markdown-done')) return; // v-botui-markdown="false"
    el.innerHTML = _parseMarkDown(el.textContent);
    el.setAttribute('botui-markdown-done', true); // mark the node as already parsed
});
```

### PR DESCRIPTION
**Pull request by stroncium**

### CODE REVIEW

**Comment by stroncium** [comment]
@moinism Not sure about this fix being idiomatic, but it's clean and working and fixes mentioned issues.

Also, you have `build` files in repo which shouldn't be there.

**Comment by iskrisis** [comment]
This fixed problems for me.

**Comment by dvolonnino** [comment]
This works for me to. Will this be committed?

**Comment by logikblok** [comment]
Hi @moinism do you have any thoughts on commiting this?

**Pull request closed without merging**
